<?php

use Illuminate\Support\Facades\Event;
use LonelyLights\Prosetta\Contracts\TranslationDriver;
use LonelyLights\Prosetta\Enums\TranslationStatus;
use LonelyLights\Prosetta\Events\ExportCompleted;
use LonelyLights\Prosetta\Export\Exporter;
use LonelyLights\Prosetta\Models\Translation;
use LonelyLights\Prosetta\Queries\KeyFinder;
use LonelyLights\Prosetta\Review\ReviewService;
use LonelyLights\Prosetta\Support\Fingerprint;
use LonelyLights\Prosetta\Sync\Syncer;
use LonelyLights\Prosetta\Testing\FakeTranslationDriver;
use LonelyLights\Prosetta\Translation\Translator;

beforeEach(function () {
    $this->useFixtureApp();
    $this->seedLocales();
    app(Syncer::class)->sync();
});

const SPANISH_IN_USE = 'Este código de acceso se está usando para registrarse en otro dispositivo. Si ese registro no se completa, quedará libre en unos minutos.';

it('exports approved values only by default, in source key order', function () {
    app(Exporter::class)->export(['es'], ['identity']);

    expect(file_get_contents($this->fixture.'/modules/Identity/Lang/es/onboarding.php'))->toBe(<<<PHP
<?php

/*
 * Generated by Prosetta from identity::en/onboarding.php. Edit the source file or use Prosetta;
 * hand edits here are imported for review on the next sync.
 */

return [
    'toast' => [
        'accessCode' => [
            'inUse' => 'Este código de acceso se está usando para registrarse en otro dispositivo. Si ese registro no se completa, quedará libre en unos minutos.',
        ],
    ],
];

PHP);
});

it('exports drafts when asked, with placeholders intact', function () {
    app()->instance(TranslationDriver::class, new FakeTranslationDriver);
    app(Translator::class)->translate(['es'], ['identity'], queue: false);

    app(Exporter::class)->export(['es'], ['identity'], includeDrafts: true);

    expect(file_get_contents($this->fixture.'/modules/Identity/Lang/es/onboarding.php'))->toBe(<<<PHP
<?php

/*
 * Generated by Prosetta from identity::en/onboarding.php. Edit the source file or use Prosetta;
 * hand edits here are imported for review on the next sync.
 */

return [
    'toast' => [
        'accessCode' => [
            'capReached' => 'Registration has a :minutes-minute limit, so the access code was released. Enter it again to start over. [es]',
            'inUse' => 'Este código de acceso se está usando para registrarse en otro dispositivo. Si ese registro no se completa, quedará libre en unos minutos.',
            'timedOut' => 'Your registration paused for more than five minutes, so the access code was released. Enter it again to continue. [es]',
        ],
    ],
];

PHP);
});

it('never exports a candidate with blocking issues, even with drafts', function () {
    app()->instance(TranslationDriver::class, (new FakeTranslationDriver)->dropPlaceholders());
    app(Translator::class)->translate(['es'], ['identity'], queue: false);

    app(Exporter::class)->export(['es'], ['identity'], includeDrafts: true);

    expect(file_get_contents($this->fixture.'/modules/Identity/Lang/es/onboarding.php'))
        ->not->toContain('capReached')
        ->toContain('timedOut');
});

it('never writes the source locale', function () {
    $before = file_get_contents($this->fixture.'/lang/en/auth.php');

    $report = app(Exporter::class)->export();

    expect(file_get_contents($this->fixture.'/lang/en/auth.php'))->toBe($before)
        ->and(collect($report->written)->filter(fn (string $path) => str_contains($path, '/en/')))->toBeEmpty();
});

it('does not rewrite unchanged files', function () {
    app(Exporter::class)->export(['es']);
    $report = app(Exporter::class)->export(['es']);

    expect($report->written)->toBe([])
        ->and($report->unchanged)->toContain($this->fixture.'/lang/es/auth.php');
});

it('refuses excluded paths', function () {
    config()->set('prosetta.exclude_paths', [$this->fixture.'/lang/es']);
    $before = file_get_contents($this->fixture.'/lang/es/auth.php');

    $report = app(Exporter::class)->export(['es']);

    expect($report->refused)->toContain($this->fixture.'/lang/es/auth.php')
        ->and(file_get_contents($this->fixture.'/lang/es/auth.php'))->toBe($before);
});

it('writes nothing on a dry run', function () {
    $before = file_get_contents($this->fixture.'/lang/es/auth.php');

    $report = app(Exporter::class)->export(['es'], dryRun: true);

    expect($report->dryRun)->toBeTrue()
        ->and($report->written)->toContain($this->fixture.'/lang/es/auth.php')
        ->and(file_get_contents($this->fixture.'/lang/es/auth.php'))->toBe($before)
        ->and(is_file($this->fixture.'/lang/ar/auth.php'))->toBeFalse();
});

it('round-trips: exporting then syncing finds no hand edits', function () {
    app()->instance(TranslationDriver::class, new FakeTranslationDriver);
    app(Translator::class)->translate(queue: false);
    app(Exporter::class)->export(includeDrafts: true);

    $report = app(Syncer::class)->sync();

    expect($report->handEdits)->toBe([])
        ->and($report->imported)->toBe(0)
        ->and($report->hasChanges())->toBeFalse();
});

it('exports JSON keys whole with readable unicode', function () {
    $key = app(KeyFinder::class)->find('json:Version 2.0 is ready.');
    Translation::query()->create([
        'key_id' => $key->id, 'locale' => 'es', 'value' => 'La versión 2.0 está lista.', 'source_hash' => $key->source_hash,
        'approved_value' => 'La versión 2.0 está lista.', 'approved_source_hash' => $key->source_hash, 'status' => TranslationStatus::Approved,
    ]);

    app(Exporter::class)->export(['es']);

    expect(json_decode(file_get_contents($this->fixture.'/lang/es.json'), true))->toBe([
        'Save changes' => 'Guardar cambios', 'Version 2.0 is ready.' => 'La versión 2.0 está lista.',
    ])->and(file_get_contents($this->fixture.'/lang/es.json'))->toContain('versión');
});

it('exports list arrays back as lists', function () {
    foreach (['admin/settings.steps.0' => 'Abre el menú', 'admin/settings.steps.1' => 'Elige un idioma'] as $ref => $value) {
        $key = app(KeyFinder::class)->find($ref);
        Translation::query()->create([
            'key_id' => $key->id, 'locale' => 'es', 'value' => $value, 'source_hash' => $key->source_hash,
            'approved_value' => $value, 'approved_source_hash' => $key->source_hash, 'status' => TranslationStatus::Approved,
        ]);
    }

    app(Exporter::class)->export(['es']);

    expect(require $this->fixture.'/lang/es/admin/settings.php')->toBe(['steps' => ['Abre el menú', 'Elige un idioma']])
        ->and(app(Syncer::class)->sync()->handEdits)->toBe([]);
});

it('drops obsolete keys but keeps the file', function () {
    file_put_contents($this->fixture.'/lang/en/auth.php', "<?php return ['throttle' => 'Too many login attempts. Please try again in :seconds seconds.'];");
    app(Syncer::class)->sync();

    app(Exporter::class)->export(['es']);

    expect(require $this->fixture.'/lang/es/auth.php')->toBe([]);
});

it('records what it wrote and announces the export', function () {
    Event::fake([ExportCompleted::class]);

    app(Exporter::class)->export(['es'], ['identity']);
    $inUse = app(KeyFinder::class)->find('identity::onboarding.toast.accessCode.inUse')->translations->firstWhere('locale', 'es');

    expect($inUse->exported_hash)->toBe(Fingerprint::of(SPANISH_IN_USE));
    Event::assertDispatched(ExportCompleted::class);
});

it('refuses to overwrite a hand edit that sync has not imported yet', function () {
    file_put_contents($this->fixture.'/lang/es/auth.php', "<?php return ['failed' => 'Credenciales incorrectas.'];");

    $report = app(Exporter::class)->export(['es']);

    expect($report->conflicts)->toHaveKey($this->fixture.'/lang/es/auth.php')
        ->and($report->conflicts[$this->fixture.'/lang/es/auth.php'])->toBe(['failed'])
        ->and(require $this->fixture.'/lang/es/auth.php')->toBe(['failed' => 'Credenciales incorrectas.'])
        ->and(app(Syncer::class)->sync()->handEdits)->toBe(['es auth.failed']);
});

it('refuses to overwrite a target file it has never synced', function () {
    mkdir($this->fixture.'/lang/fr');
    file_put_contents($this->fixture.'/lang/fr/auth.php', "<?php return ['failed' => 'Identifiants incorrects.'];");
    \LonelyLights\Prosetta\Models\Locale::findByCode('fr')->update(['translated' => true]);

    $report = app(Exporter::class)->export(['fr']);

    expect($report->conflicts)->toHaveKey($this->fixture.'/lang/fr/auth.php')
        ->and(require $this->fixture.'/lang/fr/auth.php')->toBe(['failed' => 'Identifiants incorrects.']);
});

it('refuses keys the source does not have, and overwrites everything when forced', function () {
    file_put_contents($this->fixture.'/lang/es/auth.php', "<?php return ['failed' => 'Estas credenciales no coinciden con nuestros registros.', 'stray' => 'Suelto'];");

    $refused = app(Exporter::class)->export(['es']);
    $forced = app(Exporter::class)->export(['es'], force: true);

    expect($refused->conflicts[$this->fixture.'/lang/es/auth.php'])->toBe(['stray'])
        ->and($forced->conflicts)->toBe([])
        ->and(require $this->fixture.'/lang/es/auth.php')->toBe(['failed' => 'Estas credenciales no coinciden con nuestros registros.']);
});

it('exports what reviewers approved without needing drafts', function () {
    app()->instance(TranslationDriver::class, new FakeTranslationDriver);
    app(Translator::class)->translate(['es'], ['identity'], queue: false);
    app(ReviewService::class)->approveClean('es', 'identity');

    app(Exporter::class)->export(['es'], ['identity']);
    $accessCode = (require $this->fixture.'/modules/Identity/Lang/es/onboarding.php')['toast']['accessCode'];

    expect(array_keys($accessCode))->toBe(['capReached', 'inUse', 'timedOut'])
        ->and($accessCode['capReached'])->toContain(':minutes');
});
