<?php

declare(strict_types=1);

namespace LonelyLights\Prosetta\Export;

use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use LonelyLights\Prosetta\Contracts\LocaleSource;
use LonelyLights\Prosetta\Data\LocaleDescriptor;
use LonelyLights\Prosetta\Discovery\LangReader;
use LonelyLights\Prosetta\Discovery\LangRoot;
use LonelyLights\Prosetta\Discovery\RootDiscovery;
use LonelyLights\Prosetta\Enums\FileFormat;
use LonelyLights\Prosetta\Enums\TranslationStatus;
use LonelyLights\Prosetta\Events\ExportCompleted;
use LonelyLights\Prosetta\Exceptions\LangFileException;
use LonelyLights\Prosetta\Exceptions\ProsettaException;
use LonelyLights\Prosetta\Models\Translation;
use LonelyLights\Prosetta\Models\TranslationFile;
use LonelyLights\Prosetta\Models\TranslationKey;
use LonelyLights\Prosetta\Support\Fingerprint;
use LonelyLights\Prosetta\Support\KeyRef;
use LonelyLights\Prosetta\Support\PathFilter;
use LonelyLights\Prosetta\Support\Settings;

/**
 * Writes target-locale files for root and module lang folders in the source
 * file's key order. Never writes the source locale, never deletes a file,
 * never writes an excluded path, and never rewrites an unchanged file. A
 * target file holding anything Prosetta did not write itself (a hand edit
 * not yet synced, a file never synced, a key the source lacks) is left
 * alone and reported as a conflict unless the export is forced.
 */
final readonly class Exporter {
    /** Starts the header of every PHP file Prosetta writes; a file without it was written by someone else. */
    public const string GENERATED = 'Generated by Prosetta';

    public function __construct(
        private RootDiscovery $discovery,
        private LangReader $reader,
        private LocaleSource $locales,
        private PathFilter $filter,
        private PhpArrayWriter $php,
        private JsonWriter $json,
        private Filesystem $files,
        private Dispatcher $events,
    ) {}

    /**
     * @param list<string> $locales
     * @param list<string> $namespaces
     * @param array<string, list<int>> $hold locale => ids of files to leave untouched, reported as held (the cycle's hand-edit guard)
     * @param bool $keepHandWritten leave existing PHP target files that Prosetta didn't generate untouched, reported as hand-written
     */
    public function export(array $locales = [], array $namespaces = [], ?bool $includeDrafts = null, bool $dryRun = false, bool $force = false, array $hold = [], bool $keepHandWritten = false): ExportReport {
        $includeDrafts ??= (bool) config('prosetta.export.include_drafts', false);
        $report = new ExportReport($dryRun);
        $source = $this->locales->source();
        $targets = array_values(array_filter(
            array_map(fn (LocaleDescriptor $locale) => $locale->code, $this->locales->targets()),
            fn (string $code) => $code !== $source && ($locales === [] || in_array($code, $locales, true)),
        ));
        $fileModel = Settings::model('file');

        foreach ($this->discovery->roots($namespaces === [] ? null : $namespaces) as $root) {
            foreach ($fileModel::query()->where('namespace', $root->namespace)->orderBy('group')->get() as $file) {
                /** @var TranslationFile $file */
                $order = array_map('strval', array_keys($this->reader->read($root, $source, $file->group, $file->format)));
                $keys = $file->keys()->whereNull('obsolete_at')->get()->keyBy(fn (TranslationKey $key) => $key->key);

                foreach ($targets as $locale) {
                    if (in_array((int) $file->getKey(), $hold[$locale] ?? [], true)) {
                        $report->held[] = ['locale' => $locale, 'path' => $this->reader->path($root, $locale, $file->group, $file->format)];

                        continue;
                    }

                    $path = $this->reader->path($root, $locale, $file->group, $file->format);

                    if ($keepHandWritten && $file->format === FileFormat::Php && is_file($path) && ! $this->generated($path)) {
                        $report->handWritten[] = ['locale' => $locale, 'path' => $path];

                        continue;
                    }

                    $this->exportFile($root, $file, $order, $keys, $source, $locale, $includeDrafts, $force, $report);
                }
            }
        }

        if (! $dryRun) {
            $this->events->dispatch(new ExportCompleted($report));
        }

        return $report;
    }

    /**
     * @param list<string> $order
     * @param Collection<string, TranslationKey> $keys
     */
    private function exportFile(LangRoot $root, TranslationFile $file, array $order, Collection $keys, string $source, string $locale, bool $includeDrafts, bool $force, ExportReport $report): void {
        $path = $this->reader->path($root, $locale, $file->group, $file->format);

        if ($this->filter->excluded($path)) {
            $report->refused[] = $path;

            return;
        }

        # The Source Group Is Gone: Leave Its Target Files as They Are, and Say So
        if ($order === []) {
            if (is_file($path)) {
                $report->orphaned[] = $path;
            }

            return;
        }

        if (! $force && ($conflicts = $this->conflicts($root, $file, $locale)) !== []) {
            $report->conflicts[$path] = $conflicts;

            return;
        }

        $translationModel = Settings::model('translation');
        $translations = $translationModel::query()->where('locale', $locale)->whereIn('key_id', $keys->modelKeys())->get()->keyBy('key_id');
        $values = [];
        $written = [];

        foreach ($order as $key) {
            $model = $keys->get($key);
            $translation = $model === null ? null : $translations->get($model->getKey());
            $value = $translation === null ? null : $this->pick($translation, $includeDrafts);

            if ($value !== null) {
                $values[$key] = $value;
                $written[$key] = [$translation, $value];
            }
        }

        # A Derived Locale Writes Only What It Changes: Laravel Falls Back to the Source for the Rest
        if (($this->locales->find($locale)?->replacements ?? []) !== []) {
            $values = $this->onlyChanged($values, $keys);
            $written = array_intersect_key($written, $values);
        }

        if ($file->format === FileFormat::Php) {
            $values = $this->withoutIncompleteLists($order, $values);
            $written = array_intersect_key($written, $values);
        }

        $exists = is_file($path);

        if ($values === [] && ! $exists) {
            return;
        }

        $content = $file->format === FileFormat::Json
            ? $this->json->render($values)
            : $this->php->render(Arr::undot($values), $this->header($file, $source));

        if ($exists && file_get_contents($path) === $content) {
            $report->unchanged[] = $path;
        } else {
            if (! $report->dryRun) {
                $this->write($path, $content);
            }

            $report->written[] = $path;
        }

        $report->keys[$path] = count($values);

        if (! $report->dryRun) {
            foreach ($written as [$translation, $value]) {
                $hash = Fingerprint::of($value);

                if ($translation->exported_hash !== $hash) {
                    $translation->update(['exported_hash' => $hash]);
                }
            }
        }
    }

    /**
     * Keys in the existing target file whose value Prosetta did not write:
     * anything without a translation row, or whose hash differs from the
     * translation's exported_hash. Obsolete keys count as known.
     *
     * @return list<string>
     */
    private function conflicts(LangRoot $root, TranslationFile $file, string $locale): array {
        try {
            $onDisk = $this->reader->read($root, $locale, $file->group, $file->format);
        } catch (LangFileException) {
            return ['(unreadable file)'];
        }

        if ($onDisk === []) {
            return [];
        }

        $keys = $file->keys()->get()->keyBy(fn (TranslationKey $key) => $key->key);
        $translationModel = Settings::model('translation');
        $translations = $translationModel::query()->where('locale', $locale)->whereIn('key_id', $keys->modelKeys())->get()->keyBy('key_id');
        $unknown = [];

        foreach ($onDisk as $key => $value) {
            $model = $keys->get((string) $key);
            $translation = $model === null ? null : $translations->get($model->getKey());

            if ($translation === null || $translation->exported_hash !== Fingerprint::of($value)) {
                $unknown[(string) $key] = Fingerprint::of($value);
            }
        }

        return array_keys(array_diff_key($unknown, $this->moved($unknown, $keys, $onDisk, $locale)));
    }

    /**
     * The unknown on-disk keys that hold exactly what Prosetta last exported
     * for a translation whose own key is not in the file: a key renamed with
     * prosetta:rename, whose old name is still on disk. Their values are
     * Prosetta's own, so the export drops them instead of reporting them.
     *
     * @param  array<string, string>  $unknown  on-disk key => fingerprint of its value
     * @param  Collection<string, TranslationKey>  $keys
     * @param  array<array-key, mixed>  $onDisk
     * @return array<string, string>
     */
    private function moved(array $unknown, Collection $keys, array $onDisk, string $locale): array {
        if ($unknown === []) {
            return [];
        }

        $present = $keys->filter(fn (TranslationKey $key, string $name) => array_key_exists($name, $onDisk))->modelKeys();
        $translationModel = Settings::model('translation');
        $exported = $translationModel::query()
            ->where('locale', $locale)
            ->whereIn('exported_hash', array_values($unknown))
            ->whereNotIn('key_id', $present)
            ->pluck('exported_hash')
            ->all();

        return array_filter($unknown, fn (string $hash) => in_array($hash, $exported, true));
    }

    /**
     * A list (keys ending .0 … .n-1) is exported whole or not at all, so no
     * item shifts position and code iterating it never meets a gap; Laravel
     * falls back to the source list until every item is translated. Keys that
     * merely look numeric (errors.404) are not a list and are left alone.
     *
     * @param list<string> $order
     * @param array<array-key, string> $values
     * @return array<array-key, string>
     */
    private function withoutIncompleteLists(array $order, array $values): array {
        $lists = [];

        foreach ($order as $key) {
            if (preg_match('/^(.+)\.(\d+)$/', $key, $match) === 1) {
                $lists[$match[1]][(int) $match[2]] = $key;
            }
        }

        foreach ($lists as $items) {
            ksort($items);

            if (array_keys($items) !== range(0, count($items) - 1)) {
                continue;
            }

            foreach ($items as $key) {
                if (! array_key_exists($key, $values)) {
                    foreach ($items as $drop) {
                        unset($values[$drop]);
                    }

                    break;
                }
            }
        }

        return $values;
    }

    /**
     * The values that differ from the source, plus every item of any list with
     * a changed item, since a list is written whole or not at all.
     *
     * @param array<array-key, string> $values
     * @param Collection<string, TranslationKey> $keys
     * @return array<array-key, string>
     */
    private function onlyChanged(array $values, Collection $keys): array {
        $changed = [];
        $lists = [];

        foreach ($values as $key => $value) {
            if ($value !== $keys->get((string) $key)?->source_value) {
                $changed[$key] = true;

                if (preg_match('/^(.+)\.\d+$/', (string) $key, $match) === 1) {
                    $lists[$match[1]] = true;
                }
            }
        }

        return array_filter(
            $values,
            fn ($key) => isset($changed[$key]) || (preg_match('/^(.+)\.\d+$/', (string) $key, $match) === 1 && isset($lists[$match[1]])),
            ARRAY_FILTER_USE_KEY,
        );
    }

    private function pick(Translation $translation, bool $includeDrafts): ?string {
        if ($includeDrafts
            && $translation->value !== null
            && $translation->status !== TranslationStatus::Rejected
            && ! $translation->hasBlockingIssues()) {
            return $translation->value;
        }

        return $translation->approved_value;
    }

    private function header(TranslationFile $file, string $source): string {
        $prefix = $file->namespace === KeyRef::ROOT ? '' : $file->namespace.'::';

        return self::GENERATED." from $prefix$source/$file->group.php. Edit the source file or use Prosetta;\nhand edits here are imported for review on the next sync.";
    }

    /** Whether Prosetta wrote this file: its header sits in the first few lines. */
    private function generated(string $path): bool {
        $head = file_get_contents($path, length: 1024);

        return $head !== false && str_contains($head, self::GENERATED);
    }

    private function write(string $path, string $content): void {
        $this->files->ensureDirectoryExists(dirname($path));
        $temporary = $path.'.prosetta-'.Str::random(8);
        $this->files->put($temporary, $content);

        if (! @rename($temporary, $path)) {
            $this->files->delete($temporary);

            throw new ProsettaException("Could not write [$path].");
        }

        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($path, true);
        }
    }
}
