<?php

use LonelyLights\Prosetta\Services\FileExporter;

describe('FileExporter', function () {
    describe('formatWithHeader', function () {
        it('formats array without header when no title or description', function () {
            $data = ['key1' => 'value1', 'key2' => 'value2'];
            $result = FileExporter::formatWithHeader($data);

            expect($result)->toStartWith("<?php\n\nreturn ");
            expect($result)->toContain("'key1' => 'value1'");
            expect($result)->not->toContain('/**');
        });

        it('adds title to header', function () {
            $data = ['key' => 'value'];
            $result = FileExporter::formatWithHeader($data, 'My Title');

            expect($result)->toContain('/**');
            expect($result)->toContain(' * My Title');
            expect($result)->toContain(' * Generated by Prosetta Translation Manager');
        });

        it('adds description to header with word wrapping', function () {
            $data = ['key' => 'value'];
            $description = 'This is a description that explains what this language file contains.';
            $result = FileExporter::formatWithHeader($data, 'Title', $description);

            expect($result)->toContain('/**');
            expect($result)->toContain(' * Title');
            expect($result)->toContain('This is a description');
        });

        it('handles empty array', function () {
            $data = [];
            $result = FileExporter::formatWithHeader($data);

            expect($result)->toContain('return array (');
        });
    });

    describe('processKeyValue', function () {
        it('adds key to language data array', function () {
            $langData = [];

            FileExporter::processKeyValue('test.key', 'Test Value', $langData, 'en', 'test/file');

            expect($langData)->toHaveKey('test.key');
            expect($langData['test.key'])->toBe('Test Value');
        });

        it('sorts keys alphabetically', function () {
            $langData = ['zebra' => 'z', 'apple' => 'a'];

            FileExporter::processKeyValue('middle', 'middle', $langData, 'en', 'test/file');

            $keys = array_keys($langData);
            expect($keys)->toBe(['apple', 'middle', 'zebra']);
        });

        it('throws exception for invalid key format', function () {
            $langData = [];

            expect(fn() => FileExporter::processKeyValue('invalid key!', 'value', $langData, 'en', 'test'))
                ->toThrow(InvalidArgumentException::class);
        });

        it('sanitizes HTML from values', function () {
            $langData = [];

            FileExporter::processKeyValue('safe.key', '<script>alert("xss")</script>Hello', $langData, 'en', 'test');

            expect($langData['safe.key'])->not->toContain('<script>');
            expect($langData['safe.key'])->toContain('Hello');
        });
    });

    describe('ensureFileExists', function () {
        it('creates directory and file when they do not exist', function () {
            $tempDir = sys_get_temp_dir() . '/prosetta_test_' . uniqid();
            $fullPath = $tempDir . '/en/test.php';
            $localPath = 'lang/en/test.php';

            try {
                FileExporter::ensureFileExists($fullPath, $localPath);

                expect(file_exists($fullPath))->toBeTrue();
                expect(is_dir(dirname($fullPath)))->toBeTrue();

                $content = file_get_contents($fullPath);
                expect($content)->toContain('return []');
            } finally {
                // Cleanup
                if (file_exists($fullPath)) {
                    unlink($fullPath);
                }
                if (is_dir($tempDir . '/en')) {
                    rmdir($tempDir . '/en');
                }
                if (is_dir($tempDir)) {
                    rmdir($tempDir);
                }
            }
        });
    });

    describe('writeToFile', function () {
        it('writes language data to file', function () {
            $tempFile = sys_get_temp_dir() . '/prosetta_test_' . uniqid() . '.php';
            $langData = ['greeting' => 'Hello', 'farewell' => 'Goodbye'];

            try {
                FileExporter::writeToFile($tempFile, $langData);

                expect(file_exists($tempFile))->toBeTrue();
                $content = file_get_contents($tempFile);
                expect($content)->toContain("'greeting' => 'Hello'");
                expect($content)->toContain("'farewell' => 'Goodbye'");
            } finally {
                if (file_exists($tempFile)) {
                    unlink($tempFile);
                }
            }
        });

        it('removes backup file after successful write', function () {
            $tempFile = sys_get_temp_dir() . '/prosetta_test_' . uniqid() . '.php';
            $backupFile = $tempFile . '.bak';

            // Create initial file
            file_put_contents($tempFile, "<?php\nreturn [];");

            try {
                FileExporter::writeToFile($tempFile, ['key' => 'value']);

                expect(file_exists($backupFile))->toBeFalse();
            } finally {
                if (file_exists($tempFile)) {
                    unlink($tempFile);
                }
                if (file_exists($backupFile)) {
                    unlink($backupFile);
                }
            }
        });
    });
});
